import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui' show SemanticsAction;

import 'package:vesper_media/platform_app.dart';
import 'package:vesper_media/app/home_page.dart';
import 'package:vesper_media/app/design/app_glass_controls.dart';
import 'package:vesper_media/app/design/app_theme_controller.dart';
import 'package:vesper_media/media/design/app_visual_theme.dart';
import 'package:vesper_media/bili/app_mode/pages/bili_hub_page.dart';
import 'package:vesper_media/bili/common/models/bili_models.dart';
import 'package:vesper_media/bili/common/models/bili_region_models.dart';
import 'package:vesper_media/bili/app_mode/pages/bili_library_page.dart';
import 'package:vesper_media/bili/common/pages/bili_playback_page.dart';
import 'package:vesper_media/bili/app_mode/pages/bili_region_hub_page.dart';
import 'package:vesper_media/bili/app_mode/pages/bili_region_video_page.dart';
import 'package:vesper_media/bili/app_mode/pages/bili_settings_page.dart';
import 'package:vesper_media/bili/common/services/bili_api_core.dart';
import 'package:vesper_media/app/services/app_settings_store.dart';
import 'package:vesper_media/bili/common/services/bili_client.dart';
import 'package:vesper_media/bili/common/services/bili_history_store.dart';
import 'package:vesper_media/bili/common/services/bili_session_store.dart';
import 'package:vesper_media/bili/common/widgets/bili_cache_download_panel.dart';
import 'package:vesper_media/bili/common/widgets/bili_qr_login_sheet.dart';
import 'package:vesper_media/bili/tv_mode/pages/bili_tv_home_page.dart';
import 'package:vesper_media/bili/tv_mode/widgets/bili_tv_qr_login_dialog.dart';
import 'package:vesper_media/bili/tv_mode/widgets/bili_tv_video_card.dart';
import 'package:vesper_media/bili/tv_mode/widgets/bili_tv_video_grid_layout.dart';
import 'package:vesper_media/bili/tv_mode/widgets/tv_directional_focus_scope.dart';
import 'package:vesper_media/media/tv/media_tv_focusable.dart';
import 'package:vesper_media/download/download.dart';
import 'package:flutter/foundation.dart';
import 'package:material_ui/material_ui.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:liquid_glass_widgets/liquid_glass_widgets.dart';
import 'package:vesper_player/vesper_player.dart';
import 'package:vesper_player_ui/vesper_player_ui.dart' as vesper_ui;

part 'widget_test_parts/support_core.dart';
part 'widget_test_parts/support_playback.dart';
part 'widget_test_parts/support_tv.dart';
part 'widget_test_parts/support_harness.dart';
part 'widget_test_parts/app_shell.dart';
part 'widget_test_parts/tv_focus_and_layout.dart';
part 'widget_test_parts/tv_library.dart';
part 'widget_test_parts/tv_content.dart';
part 'widget_test_parts/playback_recovery.dart';
part 'widget_test_parts/playback_comments.dart';
part 'widget_test_parts/playback_platforms.dart';
part 'widget_test_parts/offline_cache.dart';
part 'widget_test_parts/settings.dart';
part 'widget_test_parts/qr_login.dart';
part 'widget_test_parts/region_and_cache.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  _registerAppShellWidgetTests();
  _registerTvFocusAndLayoutWidgetTests();
  _registerTvLibraryWidgetTests();
  _registerTvContentWidgetTests();
  _registerPlaybackRecoveryWidgetTests();
  _registerPlaybackCommentsWidgetTests();
  _registerPlaybackPlatformWidgetTests();
  _registerOfflineCacheWidgetTests();
  _registerSettingsWidgetTests();
  _registerQrLoginWidgetTests();
  _registerRegionAndCacheWidgetTests();
}
