import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:path_provider/path_provider.dart';

import 'app_update_release.dart';

abstract interface class AppUpdateClient {
  Future<AppUpdateRelease?> latestRelease(AppUpdatePlatform platform);
  Future<File> download(
    AppUpdateAsset asset, {
    required void Function(int received, int total) onProgress,
  });
  void cancelDownload();
  void dispose();
}

final class AppUpdateCancelled implements Exception {}

final class AppUpdateException implements Exception {
  const AppUpdateException(this.message);
  final String message;
  @override
  String toString() => message;
}

final class GithubAppUpdateClient implements AppUpdateClient {
  GithubAppUpdateClient({
    HttpClient Function()? httpClientFactory,
    Future<Directory> Function()? temporaryDirectory,
  }) : _httpClientFactory = httpClientFactory ?? HttpClient.new,
       _temporaryDirectory = temporaryDirectory ?? getTemporaryDirectory;

  final HttpClient Function() _httpClientFactory;
  final Future<Directory> Function() _temporaryDirectory;
  final Set<HttpClient> _clients = {};
  HttpClient? _downloadClient;
  bool _downloadCancelled = false;
  bool _disposed = false;

  HttpClient _newClient() {
    if (_disposed) throw AppUpdateCancelled();
    final client = _httpClientFactory();
    client.connectionTimeout = const Duration(seconds: 15);
    client.userAgent = 'Vesper-App-Updater';
    _clients.add(client);
    return client;
  }

  void _close(HttpClient client) {
    _clients.remove(client);
    client.close(force: true);
  }

  Future<HttpClientResponse> _get(HttpClient client, Uri uri) async {
    final request = await client
        .getUrl(uri)
        .timeout(const Duration(seconds: 15));
    final response = await request.close().timeout(const Duration(seconds: 20));
    if (response.statusCode != HttpStatus.ok) {
      throw AppUpdateException(
        response.statusCode == 403 || response.statusCode == 429
            ? 'GitHub 请求暂时受限，请稍后重试。'
            : 'GitHub 请求失败（${response.statusCode}），请稍后重试。',
      );
    }
    return response;
  }

  @override
  Future<AppUpdateRelease?> latestRelease(AppUpdatePlatform platform) async {
    final client = _newClient();
    try {
      final response = await _get(
        client,
        Uri.https(
          'api.github.com',
          '/repos/$appUpdateRepository/releases/latest',
        ),
      );
      final body = await utf8.decoder
          .bind(response.timeout(const Duration(seconds: 20)))
          .join();
      final json = jsonDecode(body);
      if (json is! Map<String, dynamic>) {
        throw const FormatException('GitHub 发布信息无效');
      }
      return parseAppUpdateRelease(json, platform);
    } finally {
      _close(client);
    }
  }

  @override
  Future<File> download(
    AppUpdateAsset asset, {
    required void Function(int received, int total) onProgress,
  }) async {
    if (_downloadClient != null) {
      throw const AppUpdateException('已有安装包正在下载。');
    }
    final client = _newClient();
    _downloadClient = client;
    _downloadCancelled = false;
    File? partial;
    IOSink? sink;
    void checkCancelled() {
      if (_downloadCancelled || _disposed) throw AppUpdateCancelled();
    }

    try {
      var expectedHash = asset.sha256;
      if (expectedHash == null) {
        final checksumUrl = asset.checksumUrl;
        if (checksumUrl == null) {
          throw const AppUpdateException('安装包尚未提供完整性校验信息。');
        }
        final response = await _get(client, checksumUrl);
        final checksum = await utf8.decoder
            .bind(response.timeout(const Duration(seconds: 20)))
            .join();
        final match = RegExp(
          r'^([a-fA-F0-9]{64}) [ *](.+)$',
        ).firstMatch(checksum.trim());
        if (match == null || match.group(2) != asset.name) {
          throw const AppUpdateException('安装包校验文件无效，请稍后重试。');
        }
        expectedHash = match.group(1)!.toLowerCase();
      }
      checkCancelled();
      final directory = Directory(
        '${(await _temporaryDirectory()).path}/vesper-updates',
      );
      await directory.create(recursive: true);
      // The name is generated by the release parser, never from a URL path.
      final target = File('${directory.path}/${asset.name}');
      partial = File('${target.path}.part');
      final response = await _get(client, asset.url);
      checkCancelled();
      sink = partial.openWrite();
      var received = 0;
      onProgress(0, asset.size);
      await sink.addStream(
        response.timeout(const Duration(seconds: 30)).map((chunk) {
          checkCancelled();
          received += chunk.length;
          if (received > asset.size) {
            throw const AppUpdateException('安装包大小与发布信息不符。');
          }
          onProgress(received, asset.size);
          return chunk;
        }),
      );
      await sink.flush();
      await sink.close();
      sink = null;
      checkCancelled();
      if (received != asset.size) {
        throw const AppUpdateException('安装包下载不完整，请重新下载。');
      }
      final actualHash = await sha256.bind(partial.openRead()).first;
      checkCancelled();
      if (actualHash.toString() != expectedHash) {
        throw const AppUpdateException('安装包校验失败，请重新下载。');
      }
      return await partial.rename(target.path);
    } catch (_) {
      checkCancelled();
      rethrow;
    } finally {
      try {
        await sink?.close();
      } catch (_) {
        // Preserve the original transfer error while cleaning up its file.
      }
      try {
        if (partial != null && await partial.exists()) await partial.delete();
      } on FileSystemException {
        // A cleanup failure must not hide the download error or block retry.
      } finally {
        if (_downloadClient == client) _downloadClient = null;
        _close(client);
      }
    }
  }

  @override
  void cancelDownload() {
    final client = _downloadClient;
    _downloadCancelled = true;
    client?.close(force: true);
  }

  @override
  void dispose() {
    _disposed = true;
    cancelDownload();
    for (final client in _clients.toList()) {
      _close(client);
    }
  }
}
